###get request
GET http://localhost:3000/dashboard/slider

### post request
POST http://localhost:3000/dashboard/slider
Content-Type: application/json

{
    "img": "https://media3.s-nbcnews.com/i/newscms/2016_32/1149295/laundry-stock-today-160808-tease_8816217b49c15bf3fc07bbcd6558c2db.jpg"   
}


### post request
POST http://localhost:3000/login
Content-Type: application/json

{
    "uemail": "vhhv@123.com",
    "upass": "akc1011123"
}

###single id get request
GET http://localhost:3000/login/arpi@123.com

###single id Update request
PATCH  http://localhost:3000/data/5ea9307c5e6e612408b423eas2
Content-Type: application/json

{
    "avatar": "sadad"
}

###single id delete request
DELETE  http://localhost:3000/dashboard/slider/5f034a70a39aef435000050e

###single id get request
GET http://localhost:3000/ 