###get request
GET http://localhost:3000/dashboard/slider

### post request
POST https://scenic-lassen-volcanic-38075.herokuapp.com/dashboard/offers
Content-Type: application/json

{
    "offer_name":"Flat 10% on Wash & Iron",
    "img":"https://image.flaticon.com/icons/svg/2913/2913641.svg",
    "coupon_code":"LAUNDARY500IRON",
    "valid_till":"11 Jan 2021"   
}


### post request
POST http://localhost:3000/login
Content-Type: application/json

{
    "uemail": "vhhv@123.com",
    "upass": "akc1011123"
}

###single id get request
GET http://localhost:3000/login/arpi@123.com

###single id Update request
PATCH  http://localhost:3000/data/5ea9307c5e6e612408b423eas2
Content-Type: application/json

{
    "avatar": "sadad"
}

###single id delete request
DELETE  http://localhost:3000/dashboard/slider/5f034a70a39aef435000050e

###single id get request
GET http://localhost:3000/ 